language: python
dist: xenial
os:
  - linux

python:
  - '3.6'
  - '3.7'
  - '3.8'

cache:
  directories:
    - $HOME/.cache/pip

install:
  - ./scripts/setup.sh

script:
  - ./scripts/test.sh
  - ./scripts/example.sh
